NCATComp410/comp410_fall_2022

- pii_detect.py
- test_pii_detect.py
Initial Commit to created fork.
> Aggie Slogan merge commit

- pii_detect.py
- test_pii_detect.py
> That's What Aggies Do Commit

- test_pii_detect.py
Fixed "thats_on_1891()" to "test_thats_on_1891()"
> That's on 1891 updated commit

- pii_detect.py
- test_pii_detect.py
added my slogan to the list as well as updated the test cases.
> added slogan

- pii_detect.py
- test_pii_detect.py
Added my slogan to the current list of slogans for Sprint 1.
> Added Slogan to List

- pii_detect.py
- test_pii_detect.py
> Add Achieve Slogan

- pii_detect.py
- test_pii_detect.py
> cdwilkie slogan

- pii_detect.py
- test_pii_detect.py
Forgot to change the def name for entry #19, also changed the slogan
> Changed name of def

- pii_detect.py
- test_pii_detect.py
> cdwilkie slogan (again?)

- pii_detect.py
- test_pii_detect.py
> Added "Aggie PRIDE!" to slogan list

- pii_team_frost.py
- test_team_frost.py
> Add support for Instagram handle

- pii_team_sei.py
- test_team_sei.py
#70 Added regex functionality to find_visa_mastercard() and test cases to test_find_visa_mastercard()
> Added Support for Visa and Mastercard 

- pii_team_frost.py
- test_team_frost.py
Used Regex to help search for SSN within the given sentence. Used the AssertEqual statement to check if the function and my list match up.
> Add support for US SSN

- pii_team_t1.py
- test_team_t1.py
tried to write good test cases and have a basic function that should check that the credit card is in the correct format.
> put in visa_mastercard and wrote tests for it.

- pii_team_frost.py
- test_team_frost.py
> Add support for email

- pii_team_t2.py
- test_team_t2.py
Created test cases and guides for instagram handles for t2
> T2 instagram issue

- pii_team_t2.py
- test_team_t2.py
> Find SSN Added

- pii_team_frost.py
- test_team_frost.py
> 58 frost add support for visa mastercard

- pii_team_phantom.py
- test_team_phantom.py
Initial Mastercard commit - Phantom Troupe
> Mastercard commit

- test_team_frost.py
Removed all imports that weren't necessary to the document.
> Removed Unnecessary Imports

- pii_team_frost.py
Created the Anonymizer Function to read over the given input and anonymize key regex patterns. Since I was in charge of the SSN I added the SSN recognizer to the list as well as added 'US_SSN' to the detect_types list.
> Created Anonymizer Function and Added SSN Recognizer

- pii_team_t1.py
- test_team_t1.py
done the credit card testing and anonymizer for team 1.
> 187 pii support for credit card

- pii_team_sei.py
- test_team_sei.py
Fixed email detection and added support for detecting instagram handle
> Implement NLP Analyzer & Anonymizer
